In [1]:
import pandas as pd

In [2]:
path = './Iris.csv'
df = pd.read_csv(path)
df.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
x = df.iloc[:,:4]
y = df.iloc[:,4]

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=.80,random_state=3)

In [5]:
x_train.head()

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
14             5.8           4.0            1.2           0.2
24             4.8           3.4            1.9           0.2
139            6.9           3.1            5.4           2.1
58             6.6           2.9            4.6           1.3
8              4.4           2.9            1.4           0.2

In [7]:
#Standard scaler
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [11]:
x_train

array([[-0.04717658,  2.19102181, -1.46020619, -1.31097023],
       [-1.30521861,  0.78501851, -1.06028014, -1.31097023],
       [ 1.33666966,  0.08201686,  0.93935012,  1.19659028],
       [ 0.95925705, -0.38665091,  0.48229177,  0.14077533],
       [-1.80843543, -0.38665091, -1.34594161, -1.31097023],
       [-0.8020018 ,  1.01935239, -1.28880931, -1.31097023],
       [ 1.08506126, -0.15231702,  0.71082095,  0.6686828 ],
       [-1.68263122, -1.79265421, -1.4030739 , -1.17899336],
       [ 0.70764865, -0.85531868,  0.88221783,  0.93263654],
       [ 0.45604024, -2.02698809,  0.42515948,  0.40472907],
       [ 0.70764865, -0.62098479,  1.05361471,  1.19659028],
       [-0.04717658, -0.85531868,  0.08236572,  0.00879846],
       [-1.55682702,  1.25368628, -1.57447078, -1.31097023],
       [-0.927806  ,  1.01935239, -1.34594161, -1.17899336],
       [ 0.33023603, -0.15231702,  0.65368865,  0.80065967],
       [ 0.70764865,  0.31635074,  0.42515948,  0.40472907],
       [-0.927806  ,  0.55068463, -1.17454473, -0.91503963],
       [ 0.20443183, -0.85531868,  0.76795324,  0.53670593],
       [-0.04717658, -0.85531868,  0.76795324,  0.93263654],
       [-0.55039339, -0.15231702,  0.42515948,  0.40472907],
       [-1.30521861, -0.15231702, -1.34594161, -1.17899336],
       [-1.05361021,  0.31635074, -1.46020619, -1.31097023],
       [-0.04717658, -0.85531868,  0.76795324,  0.93263654],
       [ 1.46247387,  0.31635074,  0.53942407,  0.2727522 ],
       [ 0.33023603, -0.62098479,  0.53942407,  0.00879846],
       [-1.17941441,  0.08201686, -1.28880931, -1.4429471 ],
       [ 0.58184444,  0.78501851,  1.05361471,  1.59252089],
       [-0.927806  ,  1.72235404, -1.28880931, -1.17899336],
       [ 0.83345285, -0.15231702,  0.99648241,  0.80065967],
       [-0.17298078, -0.38665091,  0.2537626 ,  0.14077533],
       [-1.05361021,  1.25368628, -1.34594161, -1.31097023],
       [-1.30521861, -0.15231702, -1.34594161, -1.4429471 ],
       [ 1.21086546,  0.31635074,  1.22501159,  1.46054402],
       [ 0.07862763,  0.31635074,  0.59655636,  0.80065967],
       [-0.55039339,  1.48802016, -1.28880931, -1.31097023],
       [-1.30521861,  0.78501851, -1.23167702, -1.31097023],
       [-0.927806  , -1.32398644, -0.43182492, -0.12317841],
       [ 0.70764865,  0.08201686,  0.99648241,  0.80065967],
       [ 0.58184444,  0.55068463,  1.28214388,  1.72449776],
       [-1.17941441,  0.08201686, -1.28880931, -1.4429471 ],
       [ 1.08506126,  0.55068463,  1.110747  ,  1.19659028],
       [-0.17298078, -0.15231702,  0.2537626 ,  0.00879846],
       [-1.43102282,  0.31635074, -1.23167702, -1.31097023],
       [-0.927806  ,  0.78501851, -1.28880931, -1.31097023],
       [ 1.96569068, -0.62098479,  1.33927617,  0.93263654],
       [ 2.34310329,  1.72235404,  1.68206993,  1.32856715],
       [-0.04717658, -0.62098479,  0.76795324,  1.59252089],
       [-0.17298078, -0.62098479,  0.19663031,  0.14077533],
       [-0.8020018 , -0.85531868,  0.08236572,  0.2727522 ],
       [ 0.58184444, -1.79265421,  0.36802719,  0.14077533],
       [-0.927806  ,  1.72235404, -1.06028014, -1.0470165 ],
       [-0.42458919,  1.01935239, -1.4030739 , -1.31097023],
       [ 0.70764865,  0.31635074,  0.88221783,  1.46054402],
       [ 1.08506126,  0.55068463,  1.110747  ,  1.72449776],
       [ 1.33666966,  0.08201686,  0.65368865,  0.40472907],
       [ 1.58827807, -0.15231702,  1.22501159,  1.19659028],
       [ 0.07862763, -0.15231702,  0.2537626 ,  0.40472907],
       [ 2.34310329, -0.62098479,  1.68206993,  1.06461341],
       [-1.30521861,  0.08201686, -1.23167702, -1.31097023],
       [ 0.58184444, -0.62098479,  0.76795324,  0.40472907],
       [-1.93423963, -0.15231702, -1.51733849, -1.4429471 ],
       [-0.17298078, -0.62098479,  0.42515948,  0.14077533],
       [ 0.95925705, -0.15231702,  0.36802719,  0.2727522 ],
       [ 0.70764865, -0.62098479,  1.05361471,  1.32856715],
       [ 0.45604024,  0.78501851,  0.93935012,  1.46054402],
       [-0.8020018 ,  2.4253557 , -1.28880931, -1.4429471 ],
       [-0.42458919, -1.55832033,  0.02523343, -0.12317841],
       [-0.55039339,  1.95668793, -1.4030739 , -1.0470165 ],
       [ 0.33023603, -0.15231702,  0.48229177,  0.2727522 ],
       [ 0.70764865, -0.38665091,  0.3108949 ,  0.14077533],
       [ 0.20443183,  0.78501851,  0.42515948,  0.53670593],
       [-1.17941441, -0.15231702, -1.34594161, -1.31097023],
       [ 1.71408227,  0.31635074,  1.28214388,  0.80065967],
       [-0.927806  ,  1.72235404, -1.23167702, -1.31097023],
       [ 1.08506126, -1.32398644,  1.16787929,  0.80065967],
       [ 0.33023603, -0.62098479,  0.13949802,  0.14077533],
       [ 1.08506126, -0.15231702,  0.82508553,  1.46054402],
       [ 0.58184444,  0.55068463,  0.53942407,  0.53670593],
       [-0.29878498, -0.62098479,  0.65368865,  1.06461341],
       [ 0.33023603, -0.38665091,  0.53942407,  0.2727522 ],
       [-0.17298078,  1.72235404, -1.17454473, -1.17899336],
       [ 2.21729909, -0.15231702,  1.62493764,  1.19659028],
       [-0.29878498, -0.38665091, -0.08903116,  0.14077533],
       [ 0.83345285, -0.15231702,  0.82508553,  1.06461341],
       [ 0.83345285, -0.62098479,  0.48229177,  0.40472907],
       [-0.8020018 ,  0.78501851, -1.34594161, -1.31097023],
       [ 0.20443183, -0.38665091,  0.42515948,  0.40472907],
       [ 0.58184444, -1.32398644,  0.71082095,  0.93263654],
       [-1.05361021,  0.55068463, -1.34594161, -1.31097023],
       [-0.29878498, -0.85531868,  0.2537626 ,  0.14077533],
       [-0.55039339,  0.78501851, -1.17454473, -1.31097023],
       [-1.17941441,  0.08201686, -1.28880931, -1.4429471 ],
       [-0.67619759,  1.48802016, -1.28880931, -1.31097023],
       [-0.17298078, -1.08965256, -0.14616345, -0.25515528],
       [ 0.58184444, -0.85531868,  0.65368865,  0.80065967],
       [-0.42458919,  2.65968958, -1.34594161, -1.31097023],
       [-1.05361021,  1.01935239, -1.23167702, -0.78306276],
       [ 1.33666966,  0.31635074,  1.110747  ,  1.46054402],
       [-1.05361021,  0.78501851, -1.28880931, -1.31097023],
       [ 0.20443183, -2.02698809,  0.13949802, -0.25515528],
       [ 0.07862763, -0.15231702,  0.76795324,  0.80065967],
       [ 0.45604024, -0.38665091,  0.3108949 ,  0.14077533],
       [ 0.83345285,  0.31635074,  0.76795324,  1.06461341],
       [ 0.83345285, -0.15231702,  1.16787929,  1.32856715],
       [-0.29878498, -1.32398644,  0.08236572, -0.12317841],
       [-0.42458919, -1.08965256,  0.36802719,  0.00879846],
       [ 1.71408227, -0.15231702,  1.16787929,  0.53670593],
       [-1.05361021, -2.49565586, -0.14616345, -0.25515528],
       [-1.43102282,  0.31635074, -1.4030739 , -1.31097023],
       [-0.29878498, -0.15231702,  0.42515948,  0.40472907],
       [-0.42458919, -1.55832033, -0.03189886, -0.25515528],
       [-1.05361021,  0.78501851, -1.23167702, -1.0470165 ],
       [-1.05361021, -1.79265421, -0.26042804, -0.25515528],
       [ 0.20443183, -2.02698809,  0.71082095,  0.40472907],
       [ 0.20443183, -0.15231702,  0.59655636,  0.80065967],
       [ 1.83988648, -0.38665091,  1.45354076,  0.80065967],
       [-0.927806  ,  1.48802016, -1.28880931, -1.0470165 ],
       [-0.927806  ,  1.01935239, -1.34594161, -1.31097023],
       [ 2.5947117 ,  1.72235404,  1.51067305,  1.06461341],
       [-1.17941441, -1.32398644,  0.42515948,  0.6686828 ]])

In [12]:
#running the model
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [13]:
y_pred  = classifier.predict(x_test)
y_pred

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor'], dtype=object)

In [15]:
#checking accuracy
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      0.90      0.95        10
 Iris-virginica       0.91      1.00      0.95        10

       accuracy                           0.97        30
      macro avg       0.97      0.97      0.97        30
   weighted avg       0.97      0.97      0.97        30

In [25]:
# Save model
import pickle
pickle.dump(classifier, open('model.pkl', 'wb'))
pickle.dump(scaler, open('scaler.pkl', 'wb'))

In [23]:
y_pred_val = classifier.predict([[-0.9, 0.8, -1.3, -1.2]])

In [24]:
y_pred_val

array(['Iris-setosa'], dtype=object)